[package]
name = "mullvad-management-interface"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Mullvad VPN IPC. Contains types and functions for IPC clients and servers."
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.19" }
err-derive = "0.3.1"
mullvad-types = { path = "../mullvad-types" }
mullvad-paths = { path = "../mullvad-paths" }
talpid-types = { path = "../talpid-types" }
tower = "0.4"
tonic = "0.7.2"
prost = "0.10.4"
prost-types = "0.10.1"
parity-tokio-ipc = "0.9"
futures = "0.3"
tokio = { version = "1.8", features =  ["rt"] }
log = "0.4"

[target.'cfg(unix)'.dependencies]
nix = "0.23"
lazy_static = "1.0"

[build-dependencies]
tonic-build = { version = "0.7.2", default-features = false, features = ["transport", "prost"] }
