name: Verify lockfile signatures
on:
    pull_request:
        paths:
            - .github/workflows/verify-locked-down-signatures.yml
            - Cargo.lock
            - gui/package-lock.json
            - wireguard/libwg/go.sum
            - ci/keys/
            - ci/verify-locked-down-signatures.sh
            - ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
            - android/gradle/verification-metadata.xml
            - android/gradle/wrapper/gradle-wrapper.properties
    workflow_dispatch:
      inputs:
        commitDepth:
          description: "Commit depth which must include origin/master"
          required: true
          default: '50' 
          type: string
jobs:
    verify-signatures:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                ref: ${{ github.event.pull_request.head.sha }}
            - name: Verify signatures
              run: |
                git fetch --shallow-exclude=master
                #git fetch --shallow-exclude=master

                ci/verify-locked-down-signatures.sh --import-gpg-keys --whitelist origin/master
