name: Verify lockfile signatures
on:
    pull_request:
        paths:
            - .github/workflows/verify-locked-down-signatures.yml
            - Cargo.lock
            - gui/package-lock.json
            - wireguard/libwg/go.sum
            - ci/keys/
            - ci/verify-locked-down-signatures.sh
            - ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
            - android/gradle/verification-metadata.xml
            - android/gradle/wrapper/gradle-wrapper.properties
    workflow_dispatch:
      inputs:
        commitDepth:
          description: "Commit depth which must include origin/master"
          required: true
          default: '50' 
          type: string
jobs:
    verify-signatures:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                ref: ${{ github.event.pull_request.head.sha }}
            - name: Verify signatures
              run: |
                echo "git rev-list --all --count before: "
                git rev-list --all --count

                #git fetch --shallow-exclude=master

                commit_depth_pr=${{ github.event.pull_request.commits }}
                echo "Input: ${{ github.event.inputs.commitDepth }}"
                commit_depth=${commit_depth_pr:-${{ github.event.inputs.commitDepth }}}
                echo "Commit depth: $commit_depth"
                if [[ -n "$commit_depth" ]]; then
                    # Prepare enough depth for diffs with master, currently hard-coded but should probably be
                    # whatever branch is merged into
                    echo "Fetching with a depth of $commit_depth + 1"
                    git fetch --depth="$(( commit_depth + 1 ))" origin ${{ github.head_ref }} master
                fi

                echo "git rev-list --all --count after: "
                git rev-list --all --count

                echo "git rev-list origin/master --count after: "
                git rev-list origin/master --count

                ci/verify-locked-down-signatures.sh --import-gpg-keys --whitelist origin/master
